name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Tar files
      run: tar -czvf release.tar.gz .
      
    - name: Upload release asset
      uses: actions/upload-artifact@v2
      with:
        name: release.tar.gz
        path: release.tar.gz